/*
1. Salespeople with Percent Commission
From the following table, write a SQL query to select all the salespeople. 
Return salesman_id, name, city, commission with the percent sign (%).
Sample table: salesman
*/
SELECT salesman_id,
       name,
       city,
       CAST(CAST(commission * 100 AS INT) AS VARCHAR(10)) + '%' AS [Commission %]
FROM Salesman;


/*
2. Daily Order Count Format
write a SQL query to find the number of orders booked for each day. Return the result in a format like "For 2001-10-10 there are 15 orders".". 
Sample table: orders
*/
select 'For ' + convert(Varchar(20),ord_date,120) + ' there are ' + cast(count(ord_no) as varchar(10)) + ' orders'
from Orders
group by ord_date;


/*
3. All Orders Sorted by Order Number
From the following table, write a SQL query to find all the orders. Sort the result-set in ascending order by ord_no. Return all fields.  
Sample table: orders
*/

select *
from Orders
order by ord_no;

/*
4. Orders Sorted by Date Descending
From the following table, write a SQL query to find all the orders. Sort the result-set in descending order by ord_date. Return all fields. 
Sample table: orders
*/
select *
from Orders
order by ord_date desc;


/*
5. Orders Sorted by Date & Amount Descending
From the following table, write a SQL query to find all the orders. Sort the result-set in descending order by ord_date and purch_amt. Return all fields.  
Sample table: orders
*/

select ord_date, purch_amt, ord_no, customer_id, salesman_id
from Orders
order by ord_date, purch_amt desc;


/*
6. Customers Sorted by ID
From the following table, write a SQL query to find all the customers. Sort the result-set by customer_id. Return cust_name, city, grade. 
Sample table: customer
*/
select cust_name, city, grade
from Customer
order by customer_id;



/*
7. Maximum Purchase per Salesperson per Date
From the following table, write a SQL query that calculates the maximum purchase amount generated by each salesperson for each order date. 
Sort the result-set by salesperson id and order date in ascending order. Return salesperson id, order date and maximum purchase amount. 
Sample table: orders
*/
select salesman_id, ord_date, max(purch_amt) as [max purch amount]
from Orders
group by salesman_id, ord_date
order by salesman_id,ord_date;


/*
8. Customers Sorted by Third Field
From the following table, write a SQL query to find all the customers. 
Sort the result-set in descending order on 3rd field. Return customer name, city and grade.  
Sample table: customer
*/
select cust_name, city, grade
from Customer
order by grade desc;

/*
9. Customer Unique Orders and Maximum Purchase
From the following table, write a SQL query that counts the unique orders and the highest purchase amount for each customer. 
Sort the result-set in descending order on 2nd field. 
Return customer ID, number of distinct orders and highest purchase amount by each customer. 
Sample table: orders
*/

select customer_id, count(distinct ord_no) [unique order count], max(purch_amt) [maximum purchase amount]
from Orders
group by customer_id
order by count(distinct ord_no) desc;

/*
10. Daily Totals with Commission Calculation
From the following table, write a SQL query to calculate the summation of purchase amount, total commission (15% for all salespeople) by each order date. 
Sort the result-set on order date. 
Return order date, summation of purchase amount and commission.
Sample table : orders
*/
select ord_date, sum(purch_amt) [Sum], CAST(sum(purch_amt) * 0.15 as DECIMAL(10,2)) [commission]
from Orders
group by ord_date

/*----------------------------------------------------------------- END -------------------------------------------------------------------------------------------*/