/*
1. Display Orders Issued by Salesman 'Paul Adam'
From the following tables, write a SQL query to find all the orders issued by the salesman 'Paul Adam'. Return ord_no, purch_amt, ord_date, customer_id and salesman_id.
*/

SELECT O.ORD_NO, O.PURCH_AMT, O.ORD_DATE, O.CUSTOMER_ID, S.SALESMAN_ID
FROM SALESMAN S
JOIN ORDERS O
ON O.SALESMAN_ID = S.SALESMAN_ID
WHERE S.NAME = 'PAUL ADAM';

/*
2. Display Orders Generated by London-Based Salespeople
From the following tables write a SQL query to find all orders generated by London-based salespeople. Return ord_no, purch_amt, ord_date, customer_id, salesman_id.
*/

SELECT O.ORD_NO, O.PURCH_AMT, O.ORD_DATE, O.CUSTOMER_ID, S.SALESMAN_ID
FROM SALESMAN S
JOIN ORDERS O
ON O.SALESMAN_ID = S.SALESMAN_ID
WHERE S.CITY = 'LONDON';

/*
3. Display Orders from Salespeople Handling Customer ID 3007
From the following tables write a SQL query to find all orders generated by the salespeople who may work for customers whose id is 3007. 
Return ord_no, purch_amt, ord_date, customer_id, salesman_id.
*/

SELECT ORD_NO,
       PURCH_AMT,
       ORD_DATE,
       CUSTOMER_ID,
       SALESMAN_ID
FROM ORDERS
WHERE SALESMAN_ID = (SELECT SALESMAN_ID FROM CUSTOMER WHERE CUSTOMER_ID = 3007);

/*
4. Display Orders Exceeding Average Value on 10-Oct-2012
From the following tables write a SQL query to find the order values greater than the average order value of 10th October 2012. 
Return ord_no, purch_amt, ord_date, customer_id, salesman_id.
*/

SELECT * FROM ORDERS
WHERE PURCH_AMT > (
SELECT AVG(PURCH_AMT) FROM ORDERS
WHERE ORD_DATE = '2012-10-10');

/*
5. Display Orders Generated in New York City
From the following tables, write a SQL query to find all the orders generated in New York city. Return ord_no, purch_amt, ord_date, customer_id and salesman_id.
*/

SELECT * FROM ORDERS
WHERE CUSTOMER_ID IN (
SELECT CUSTOMER_ID
FROM CUSTOMER
WHERE CITY = 'NEW YORK');

/*
6. Display Commission of Salespeople in Paris
Display the commission of salespeople who serve customers located in Paris. (question has been corrected)
*/

SELECT COMMISSION
FROM SALESMAN
WHERE SALESMAN_ID IN 
(SELECT SALESMAN_ID
FROM CUSTOMER
WHERE CITY = 'PARIS');

/*
7. (question has been corrected)
Write a SQL query to display the customer whose customer_id is equal to the salesman_id − 2001 of the salesperson named Mc Lyon.
*/

SELECT *
FROM CUSTOMER
WHERE CUSTOMER_ID = (SELECT SALESMAN_ID FROM SALESMAN WHERE NAME = 'MC LYON') - 2001;

/*
8. Count of Customers with Above-Average Grades in New York City
From the following tables write a SQL query to count the number of customers with grades above the average in New York City. Return grade and count.  
*/
SELECT GRADE, COUNT(*) COUNT_
FROM CUSTOMER
GROUP BY GRADE
HAVING GRADE > (
SELECT AVG(GRADE) FROM CUSTOMER WHERE CITY = 'NEW YORK')

/*
9. Display Orders of Salespeople with Maximum Commission
From the following tables, write a SQL query to find those salespeople who earned the maximum commission. 
Return ord_no, purch_amt, ord_date, and salesman_id.
*/

SELECT O.ORD_NO
    ,O.PURCH_AMT
    ,O.ORD_DATE
    ,S.SALESMAN_ID
FROM ORDERS O
JOIN SALESMAN S
    ON O.SALESMAN_ID = S.SALESMAN_ID
WHERE S.COMMISSION = (
SELECT MAX(COMMISSION) FROM SALESMAN );

/*
10. Display Customers Who Placed Orders on 17th August 2012
From the following tables write SQL query to find the customers who placed orders on 17th August 2012. 
Return ord_no, purch_amt, ord_date, customer_id, salesman_id and cust_name.
*/

SELECT O.* , C.CUST_NAME
FROM ORDERS O
JOIN CUSTOMER C
ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE ORD_DATE = '2012-08-17';

/*
11. Display Salespeople with More Than One Customer
From the following tables write a SQL query to find salespeople who had more than one customer. Return salesman_id and name.
*/

SELECT name 
FROM Salesman 
WHERE salesman_id IN (
    SELECT salesman_id 
    FROM Customer 
    GROUP BY salesman_id 
    HAVING COUNT(*) > 1
    )

/*
12. Display Orders with Amount Above Average Order Value
From the following tables write a SQL query to find those orders, which are higher than the average amount of the orders. 
Return ord_no, purch_amt, ord_date, customer_id and salesman_id.
*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



