/*
1. Display Orders Issued by Salesman 'Paul Adam'
From the following tables, write a SQL query to find all the orders issued by the salesman 'Paul Adam'. Return ord_no, purch_amt, ord_date, customer_id and salesman_id.
*/

select o.ord_no, o.purch_amt, o.ord_date, o.customer_id, s.salesman_id
from Salesman s
join Orders o
on o.salesman_id = s.salesman_id
where s.name = 'Paul Adam'

/*
2. Display Orders Generated by London-Based Salespeople
From the following tables write a SQL query to find all orders generated by London-based salespeople. Return ord_no, purch_amt, ord_date, customer_id, salesman_id.
*/

SELECT O.ord_no, O.purch_amt, O.ord_date, O.customer_id, S.salesman_id
FROM Salesman S
JOIN Orders O
ON O.salesman_id = S.salesman_id
WHERE S.city = 'London';

/*
3. Display Orders from Salespeople Handling Customer ID 3007
From the following tables write a SQL query to find all orders generated by the salespeople who may work for customers whose id is 3007. 
Return ord_no, purch_amt, ord_date, customer_id, salesman_id.
*/

SELECT ord_no,
       purch_amt,
       ord_date,
       customer_id,
       salesman_id
FROM Orders
WHERE salesman_id = (select salesman_id FROM Customer WHERE customer_id = 3007);

/*
4. Display Orders Exceeding Average Value on 10-Oct-2012
From the following tables write a SQL query to find the order values greater than the average order value of 10th October 2012. 
Return ord_no, purch_amt, ord_date, customer_id, salesman_id.
*/

select * from Orders
where purch_amt > (
select avg(purch_amt) from Orders
where ord_date = '2012-10-10');

/*
5. Display Orders Generated in New York City
From the following tables, write a SQL query to find all the orders generated in New York city. Return ord_no, purch_amt, ord_date, customer_id and salesman_id.
*/

select * from Orders
where customer_id in (
select customer_id
from Customer
where city = 'New York');

/*
6. Display Commission of Salespeople in Paris
Display the commission of salespeople who serve customers located in Paris. (question has been corrected)
*/

select commission
from Salesman
where salesman_id in 
(select salesman_id
from Customer
where city = 'Paris');

/*
7. (question has been corrected)
Write a SQL query to display the customer whose customer_id is equal to the salesman_id − 2001 of the salesperson named Mc Lyon.
*/

SELECT *
FROM CUSTOMER
WHERE CUSTOMER_ID = (SELECT SALESMAN_ID FROM SALESMAN WHERE NAME = 'MC LYON') - 2001;

/*
8. Count of Customers with Above-Average Grades in New York City
From the following tables write a SQL query to count the number of customers with grades above the average in New York City. Return grade and count.  
*/
select grade, count(*) count_
from Customer
group by grade
having grade > (
select avg(grade) from Customer where city = 'New York')

/*
9. Display Orders of Salespeople with Maximum Commission
From the following tables, write a SQL query to find those salespeople who earned the maximum commission. 
Return ord_no, purch_amt, ord_date, and salesman_id.
*/

SELECT O.ORD_NO
    ,O.PURCH_AMT
    ,O.ORD_DATE
    ,S.SALESMAN_ID
FROM ORDERS O
JOIN SALESMAN S
    ON O.SALESMAN_ID = S.SALESMAN_ID
WHERE S.COMMISSION = (
SELECT MAX(COMMISSION) FROM SALESMAN );


/*
10. Display Customers Who Placed Orders on 17th August 2012
From the following tables write SQL query to find the customers who placed orders on 17th August 2012. 
Return ord_no, purch_amt, ord_date, customer_id, salesman_id and cust_name.
*/

SELECT O.* , C.CUST_NAME
FROM ORDERS O
JOIN CUSTOMER C
ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE ORD_DATE = '2012-08-17';
/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



/*

*/



